package com.watchtower.common.enums;

/**
 * Types of security alerts generated by the detection engine.
 */
public enum AlertType {
    BRUTE_FORCE,
    PORT_SCAN,
    PRIVILEGE_ESCALATION,
    IMPOSSIBLE_TRAVEL,
    SUSPICIOUS_USER_AGENT,
    ANOMALOUS_LOGIN_FREQUENCY,
    ANOMALOUS_LOGIN_TIME,
    FILE_INTEGRITY_VIOLATION,
    PATTERN_MATCH,
    STATISTICAL_ANOMALY,
    ML_ANOMALY
}
